#! /bin/env python3

import os
import re
import requests

BASE_URL = "https://www.congstar.de"

login_payload = {
    "username": os.environ['CONGSTAR_USERNAME'],
    "password": os.environ['CONGSTAR_PASSWORD'],
    "defaultRedirectUrl":"/meincongstar",
    "targetPageUrlOrId":"",
    "recaptchaValue":"-"
}

s = requests.Session()
r = s.post(f'{BASE_URL}/api/auth/login', data = login_payload)

print(r)

r = s.get('https://www.congstar.de/customer-bills/monthly-grouped-bills/')

p = re.compile(r'customer-bills\/pdf\/(\d+)')

ids = p.findall(r.text)
id = ids[0]

url = f'{BASE_URL}/customer-bills/pdf/{id}'
print(url)
r = s.get(url)

file_name = f'{id}.pdf'

with open(file_name, 'wb') as f:
    f.write(r.content)

import smtplib
from os.path import basename
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import COMMASPACE, formatdate

def send_mail(send_from, send_to, subject, text, files=None, server="127.0.0.1"):
    assert isinstance(send_to, list)

    msg = MIMEMultipart()
    msg['From'] = send_from
    msg['To'] = COMMASPACE.join(send_to)
    msg['Date'] = formatdate(localtime=True)
    msg['Subject'] = subject

    msg.attach(MIMEText(text))

    for f in files or []:
        with open(f, "rb") as fil:
            part = MIMEApplication(
                fil.read(),
                Name=basename(f)
            )
        # After the file is closed
        part['Content-Disposition'] = 'attachment; filename="%s"' % basename(f)
        msg.attach(part)


    smtp = smtplib.SMTP(server)
    smtp.login(os.environ['SMTP_USERNAME'], os.environ['SMTP_PASSWORD'])
    smtp.sendmail(send_from, send_to, msg.as_string())
    smtp.close()

send_mail("congstar-api@leonard.io", ["mail@leonard.io"], "Monatliche Congstar-Rechnung", "Rechnung", files = [file_name], server = "in-v3.mailjet.com")
