name: Download invoice every month
on:
  schedule:
    - cron: "0 2 28 * *"
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy with sftp JavaScript
        run: ./congstar

